### ISSUE TITLE
Security issue when login contains special characters

### ISSUE THREAD

**Issue by pvalsecc** [Cito/pyramid_ldap3#10]
Calling `Connector.authenticate` with a login parameter like "`(example`" or "`a*`" will be replaced as is within the template setup by `config.ldap_set_login_query` leading to the possiblity to affect directly the query executed on the LDAP server.

String replaced in base_dn and filter_tmpl should be protected against special characters. To my knowledge the complete list is: `()*\/`

**Comment by Cito** [comment]
Thanks for the tip-off. Just had a quick look - your're right, `login` and `password` should be escaped in `authenticate()` where `execute()` is called, like it is already done in `user_groups()`. I'll patch this and provide a bugfix release. Luckily, as far as I see, this is not exploitable, since passing anything different from a valid username will cause an exception when binding in the second step of the `authenticate()` method and not yield a result.

**Comment by pvalsecc** [comment]
>  Luckily, as far as I see, this is not exploitable

Not true. I've tested. Let say I have a user `toto@example.com`. I can login to my application without any problem as `toto@*`.

**Comment by Cito** [comment]
Oh, right, because the second step does not check against `login`, but against `login_dn` which is the result of the search. You would still need to provide the right password.

**Comment by pvalsecc** [comment]
Indeed. The password part cannot be replaced by a *.

**Comment by Cito** [comment]
Ok, I have now patched this in 0d58fd0e. Let me know if you still see a  problem. Otherwise I'll add a note to the changelog and  push a new release.

**Comment by pvalsecc** [comment]
Thanks!
Are you sure this is needed for password?

**Comment by Cito** [comment]
This is only in case someone uses a `filter_tmpl` like `(&(user=%(login)s)(passwd=%(password)s))`.

**Comment by pvalsecc** [comment]
OK, I see. That is frightening! Un-encrypted passwords?
Regardless, you patch looks good.
Thanks for the quick fix.

**Comment by Cito** [comment]
Thanks for reporting. Bugfix release 0.3.2 is out now.
